Feature/50 add remote debugging info
elbb/bb-cplusplus pull request #51
Opened 2020-10-06 10:54 UTC by JoergZeidler

2020-11-12 12:34 UTC, mlilien commented on .vscode/launch.json
> +            "miDebuggerServerAddress": "172.18.18.100:1234",
https://stackoverflow.com/questions/29971572/how-do-i-add-environment-variables-to-launch-json-in-vscode

2020-11-12 12:35 UTC, mlilien commented on .vscode/launch.json
> +            "miDebuggerServerAddress": "172.18.18.99:1234",
https://stackoverflow.com/questions/29971572/how-do-i-add-environment-variables-to-launch-json-in-vscode

2020-11-12 12:41 UTC, mlilien commented on README.md
> +- generate with dobi a service build docker image
still ... why dobi? the only precondition is, that it is possible to deploy it to the target. can be build by dobi or ci/cd. I know we don't publish that images via ci/cd... but as a user, I would be confused if I already have a working ci/cd chain.

2020-11-12 12:42 UTC, mlilien commented on README.md
> +- store the docker image on your target
not done

2020-11-12 12:44 UTC, mlilien commented on README.md
> +docker run --rm -it --privileged --entrypoint /bin/bash -p 1234:1234 xxXXxxXX/bb-cplusplus-service-aarch64-dev
it isn't?!

2020-11-12 12:45 UTC, mlilien commented on README.md
> +This buildblock provide a visual studio code example debug file (.vscode/launch.json).
still open

2020-11-12 12:49 UTC, mlilien requested changes

2020-11-12 12:49 UTC, mlilien commented on CHANGELOG.md
> +-  added remote target debugging
added a "howto remote target debugging"

2020-11-12 12:49 UTC, mlilien commented on README.md
> +For this purpose a dobi job is provided to do the startup of a gdbserver. For demonstration purposes, the Hello World service was used as test application. To start the debug session, the following c
the "Hello World" service

2020-11-16 13:18 UTC, JoergZeidler commented on README.md
> +For this purpose a dobi job is provided to do the startup of a gdbserver. For demonstration purposes, the Hello World service was used as test application. To start the debug session, the following c
done

2020-11-16 13:18 UTC, JoergZeidler commented on CHANGELOG.md
> +-  added remote target debugging
done

2020-11-16 13:19 UTC, JoergZeidler commented on README.md
> +This buildblock provide a visual studio code example debug file (.vscode/launch.json).
done

2020-11-16 13:19 UTC, JoergZeidler commented on README.md
> +docker run --rm -it --privileged --entrypoint /bin/bash -p 1234:1234 xxXXxxXX/bb-cplusplus-service-aarch64-dev
changed

2020-11-16 13:19 UTC, JoergZeidler commented on README.md
> +- start the docker image on your target
done

2020-11-16 13:20 UTC, JoergZeidler commented on README.md
> +- store the docker image on your target
done

2020-11-16 13:20 UTC, JoergZeidler commented on README.md
> +- generate with dobi a service build docker image
doku changed

2020-11-16 13:35 UTC, JoergZeidler commented on .vscode/launch.json
> +            "miDebuggerServerAddress": "172.18.18.100:1234",
No meaningful solution found

2020-11-16 13:35 UTC, JoergZeidler commented on .vscode/launch.json
> +            "miDebuggerServerAddress": "172.18.18.99:1234",
No meaningful solution found

2020-11-17 07:55 UTC, mlilien commented on .vscode/launch.json
> +            "miDebuggerServerAddress": "172.18.18.100:1234",
for future me:
how to reference env variables: https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables
why there is no "meaningful solution": https://github.com/microsoft/vscode/issues/95371#issuecomment-614725802

2020-11-17 08:03 UTC, mlilien requested changes

2020-11-17 11:45 UTC, JoergZeidler commented on README.md
> +location of the gdb-multiarch debugger of your host system
cahnged

2020-11-17 11:46 UTC, JoergZeidler commented on README.md
> +- miDebuggerServerAddress: 172.20.0.1:1234<br>
handling changed.

2020-11-17 11:56 UTC, mlilien approved these changes

2020-11-17 12:31 UTC, merged